### PR TITLE
Feature: User counter

### PR DESCRIPTION
**Pull request by bramaudi**
Closes last task in #16 

## Description

Add users count in homepage.

image

## Whats going on this PR?

1. Creating `users` table in supabase, see updated SQL query in README.
2. Creating simple function in `src/pages/api/auth/login.ts` to add user if not exists in `users` table.
3. Add users counter component and show in index (homepage).

I also update the supabase client types, this should be better than leave it to `any`.

### CODE REVIEW

**Review by mazipan — CHANGES_REQUESTED** [review]
I didn't see any changes on readme

**Comment by mazipan** [comment]
Also try to run `yarn run build` on your local

**Comment by bramaudi** [comment]
My bad didn't testing to build first on my local, this commit https://github.com/bramaudi/ksana.in/commit/48498ef2e19044a9c6a7a0faf5587d9d6544216b should fix the problem.

**Review by mazipan — APPROVED** [review]
Looks good, lets ship this!

**Pull request merged**
